### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dcharbonnier** [RosCoCorp/Gstreamer-WebRTC-SFU#1]
maybe useful to mention on the readme that this project is not working
http://gstreamer-devel.966125.n4.nabble.com/Gstreamer-WebRTC-SFU-td4686573.html

**Comment by seeme-o** [comment]
This project hasn't posted an actual release. Assuming it works is on you, not the author. Many projects on Github are WIP, that's sort of the point of collaborative source management.

**Comment by dcharbonnier** [comment]
I guess you @need-sleep, I'm not expecting anything from the author and I don't think I'm even complaining about anything. As you know, I'm stupid and assumed after reading the commits that this project was working and I've wasted some time. I've also learned few stuff and anyway as I said I don't expect anything from the author or said anything bad.
Instead of walking away when I realized it I left an issue so the next stupid person (like me) may benefit from this information. I hope you can learn something from that. But cursing people is really a waste of time.

**Comment by royrscb** [comment]
@dcharbonnier I closed the issue because i explained in the READ ME whats the current state of the project, im sorry if you wasted time because the project is not done, but as @need-sleep said, it was not finished and nowhere says it is.
I hope with my detailed explanation of the project state there is no more confusions.
